# Default configuration for GCodeGen

# Machine parameters
machine:
  name: "H.Airbrush"
  bed_size_x: 400  # mm
  bed_size_y: 400  # mm
  head_offsets:
    tool0:
      x: 0  # mm
      y: 0  # mm
    tool1:
      x: 10  # mm
      y: 0  # mm
  safe_z: 10  # mm
  z_min: 4.0  # mm
  z_max: 80.0  # mm
  travel_speed: 24000  # mm/min
  work_speed: 3000  # mm/min
  z_speed: 1200  # mm/min
  skip_homing: false

# G-code commands
gcode:
  start_commands:
    - "G21 ; Set units to millimeters"
    - "G90 ; Use absolute coordinates"
    - "M83 ; Use relative distances for extrusion"
    - "G28 X Y ; Home X and Y"
    - "G1 Z10 F1000 ; Raise Z to safe height"
  end_commands:
    - "G1 Z10 F1000 ; Raise Z"
    - "G28 X Y ; Home X and Y"
    - "M84 ; Disable motors"
  tool_change_commands:
    tool0:
      - "T0 ; Select tool 0"
      - "M400 ; Wait for moves to complete"
    tool1:
      - "T1 ; Select tool 1"
      - "M400 ; Wait for moves to complete"

# SVG parameters
svg:
  default_units: "mm"  # mm, in, px
  dpi: 96  # For px to mm conversion
  invert_y: true  # Invert Y coordinates (SVG has Y=0 at top)
  origin: "bottom-left"  # bottom-left, center, top-left

# U axis parameters (Brush A flow control)
u_axis:
  min: 0.0  # Fully closed (0.0 mm)
  max: 4.0  # Fully open (4.0 mm)
  dead_zone: 0.8  # Lower 20% is effectively off (0.0-0.8 mm)
  feedrate: 200  # Feedrate for U axis movement in mm/min

# V axis parameters (Brush B flow control)
v_axis:
  min: 0.0  # Fully closed (0.0 mm)
  max: 4.0  # Fully open (4.0 mm)
  dead_zone: 0.8  # Lower 20% is effectively off (0.0-0.8 mm)
  feedrate: 200  # Feedrate for V axis movement in mm/min

# Paint flow scaling parameters
paint_flow_base: 0.05      # Baseline paint flow (0.0-0.2 recommended, default 0.1)
paint_flow_max: 0.5        # Maximum paint flow (0.1-1.0 recommended, default 0.5)
paint_flow_width_factor: 0.01  # Flow increase per mm of stroke width (0.01-0.1, default 0.05)
paint_flow_opacity_factor: 0.1  # Flow scaling based on opacity (0.1-1.0, default 0.4)
feedrate_z_exponent: 1.2   # Exponent for Z-based feedrate scaling (1.2 = gentle, 2.0 = strict)
feedrate_min: 1000         # Minimum feedrate in mm/min

# Tool definitions
tools:
  tool0:
    name: "Black"
    color: "#000000"
    min_width: 0.3  # mm
    max_width: 2.0  # mm
    width_to_flow_factor: 1.0  # Flow multiplier based on width
  tool1:
    name: "White"
    color: "#FFFFFF"
    min_width: 0.3  # mm
    max_width: 2.0  # mm
    width_to_flow_factor: 1.0  # Flow multiplier based on width

# Base feedrate in mm/min (recommended 1000-3000, default 1500)
base_feedrate: 48000 