; Generated by GCodeGen 0.1.0
; Input file: calibration-letter.svg
G21 ; Set units to millimeters
G90 ; Use absolute coordinates
; H.Airbrush Dual-Airbrush Plotter G-code
; Generated by GCodeGen
M451 ; CNC mode
G17 ; X-Y plane
G21 ; mm units
G90 ; Absolute positioning
M17 ; Enable all motors
M564 H1 S1 ; Enforce soft limits and require homing
G28 ; Home all axes
M84 S0 ; No stepper timeout
; ===== AIRBRUSH SYSTEM INITIALIZATION =====
; 1. Turn off all air solenoids
M106 P2 S0 ; Brush A air off
M106 P3 S0 ; Brush B air off
G4 P500 ; Wait for air to stop completely
; 2. Ensure U and V axes are at minimum position (closed)
G1 U0.000 F200.0 ; Close Brush A flow
G1 V0.000 F200.0 ; Close Brush B flow
M400 ; Wait for stepper motion to complete
; --- Tool Selection ---
T0 ; Select Tool 0 (Brush A) as the default tool
; STEPPER AND FAN CONFIGURATION:
; - Brush A: Air=Fan2, Flow=U axis (0.0-4.0mm, dead zone 0.0-0.8mm)
; - Brush B: Air=Fan3, Flow=V axis (0.0-4.0mm, dead zone 0.0-0.8mm)
; ===== END AIRBRUSH SYSTEM INITIALIZATION =====

; Width clamped from 0.53mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y242.358 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y242.358 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 0.79mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y235.744 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y235.744 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.06mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y229.129 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y229.129 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.59mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y221.192 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y221.192 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.12mm
; Opacity: 1.00
; Brush: A
; Z-height: 8.04mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y211.931 F24000.000
M400 ; Wait for XY movement to complete
G1 Z8.039 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y211.931 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.65mm
; Opacity: 1.00
; Brush: A
; Z-height: 10.05mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z10.049 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y201.348 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y201.348 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 3.70mm
; Opacity: 1.00
; Brush: A
; Z-height: 14.07mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z14.068 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y189.442 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y189.442 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 4.76mm
; Opacity: 1.00
; Brush: A
; Z-height: 18.09mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z18.087 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y176.213 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y176.213 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 6.35mm
; Opacity: 1.00
; Brush: A
; Z-height: 24.12mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z24.117 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y161.660 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y161.660 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 7.94mm
; Opacity: 1.00
; Brush: A
; Z-height: 30.15mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z30.146 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y145.785 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y145.785 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 10.05mm
; Opacity: 1.00
; Brush: A
; Z-height: 38.18mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G1 Z38.184 F1200.000
M400 ; Wait for Z movement to complete
G0 X21.167 Y128.588 F24000.000
M400 ; Wait for XY movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y128.588 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y104.775 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y104.775 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y95.515 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y95.515 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y86.254 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y86.254 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y76.994 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y76.994 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y67.733 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y67.733 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y58.473 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y58.473 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; Width clamped from 1.00mm to 2.00mm within [2.00,25.00] mm
; ===== STROKE PARAMETERS =====
; Color: #000000
; Width: 2.00mm
; Opacity: 1.00
; Brush: A
; Z-height: 7.60mm
; Paint flow: 0.95 -> U3.840mm
; Feedrate: 6000.0mm/min
; START BRUSH A
T0 ; Select Tool 0 (Brush A)
G0 X21.167 Y49.212 F24000.000
M400 ; Wait for XY movement to complete
G1 Z7.596 F1200.000
M400 ; Wait for Z movement to complete
G1 F6000.000
M106 P2 S1 ; Air on at motion start
G1 X194.733 Y49.212 U3.840
M400 ; Wait for drawing to complete
; STOP BRUSH A
G1 U0.000 F200.0 ; Close Brush A flow
M106 P2 S0 ; Brush A air off
G1 Z10.000 F1200.000 ; Raise to safe Z if below threshold
M400 ; Wait for Z movement to complete
; === PATH END ===

; ===== MACHINE CLEANUP =====
; Return to home position with Tool 0
T0 ; Select Tool 0 (Brush A)
G0 X0 Y0 F24000
M400 ; Wait for movement to complete
M564 H1 S1 ; Enforce soft limits
; Turn off all airbrush systems
G1 U0.000 F200.0 ; Close Brush A flow
G1 V0.000 F200.0 ; Close Brush B flow
M106 P2 S0 ; Brush A air off
M106 P3 S0 ; Brush B air off
G4 P500 ; Allow air to stop completely
M18 ; Disable all motors
; End of G-code
